# Generated by Django 5.2.8 on 2026-01-23 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_contact_request_from_to'),
        ),
    ]
