# Generated by Django 5.2.8 on 2026-01-31 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_contact_unique_contact_request_from_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Зона', max_length=120)),
                ('polygon', models.JSONField()),
                ('arrive_time', models.TimeField(blank=True, null=True)),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('remind_minutes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences_as_child', to=settings.AUTH_USER_MODEL, verbose_name='Ребёнок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL, verbose_name='Родитель-владелец')),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inside', models.BooleanField(default=False)),
                ('last_entered_at', models.DateTimeField(blank=True, null=True)),
                ('last_exited_at', models.DateTimeField(blank=True, null=True)),
                ('arrive_notified', models.JSONField(default=list)),
                ('depart_notified', models.JSONField(default=list)),
                ('notify_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geofence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='sos.geofence')),
            ],
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['parent', 'child', 'is_active'], name='sos_geofenc_parent__a6b251_idx'),
        ),
    ]
