# Generated by Django 5.2.8 on 2025-11-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Гос. служба',
                'verbose_name_plural': 'Гос. службы',
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительно (необязательно)')),
                ('city', models.CharField(max_length=400, verbose_name='Город')),
                ('street', models.CharField(max_length=400, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=400, verbose_name='Номер здания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gov.service', verbose_name='Гос. служба')),
            ],
            options={
                'verbose_name': 'Пункт гос. службы',
                'verbose_name_plural': 'Пункты гос. служб',
            },
        ),
    ]
