# Generated by Django 5.2.8 on 2026-03-26 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('invite_code', models.CharField(max_length=8, unique=True, verbose_name='Код приглашения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'TOUR_AGENCY'}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_groups', to=settings.AUTH_USER_MODEL, verbose_name='Тур-агент')),
            ],
            options={
                'verbose_name': 'Группа туристов',
                'verbose_name_plural': 'Группы туристов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активный участник'), ('left', 'Покинул группу'), ('removed', 'Удален из группы')], default='pending', max_length=20, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tour.tourgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(limit_choices_to={'role__in': ['TOURIST', 'USER']}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Участники группы',
                'ordering': ['joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Планируемая длительность (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_sessions', to='tour.tourgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Сессия тура',
                'verbose_name_plural': 'Сессии тура',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('polygon', models.JSONField(help_text='Массив точек [{lat: number, lng: number}, ...]', verbose_name='Полигон зоны')),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта центра')),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота центра')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='tour.tourgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Зона тура',
                'verbose_name_plural': 'Зоны тура',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта нарушения')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота нарушения')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Время уведомления')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_violations', to='tour.tourgroupmember', verbose_name='Участник')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='tour.toursession', verbose_name='Сессия')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='tour.tourzone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Нарушение зоны',
                'verbose_name_plural': 'Нарушения зоны',
                'ordering': ['-notified_at'],
            },
        ),
    ]
