# Generated by Django 5.2.8 on 2026-03-14 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpushsubscription',
            options={'verbose_name': 'Web Push подписка', 'verbose_name_plural': 'Web Push подписки'},
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text='Уникальный ID устройства', max_length=255, null=True)),
                ('registration_id', models.TextField(help_text='FCM registration token', unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web (FCM)')], default='android', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM устройство',
                'verbose_name_plural': 'FCM устройства',
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_fcmdev_user_id_35e892_idx')],
            },
        ),
    ]
