# Generated by Django 5.2.8 on 2026-04-16 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('password_change', 'Смена пароля'), ('email_change', 'Смена почты')], max_length=20, verbose_name='Действие')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP код действия',
                'verbose_name_plural': 'OTP коды действий',
            },
        ),
    ]
